import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const font = Oswald({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased m-auto bg-gray-400/30`}>
        <main className="text-card-foreground container p-10 flex flex-col max-w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
